### ISSUE TITLE
이메일 인증 구현

### ISSUE THREAD

**Issue by green-21** [4-ak/sooot#10]
이메일 인증에 대한 공부와 구현

## todos
- [x] golang에서 이메일을 전송하는 방법에 대해서 공부한다.
- [x] 실습 프로젝트를 진행한다.
- [x] 인증번호를 생성하고 유지하는 방법을 연구한다.
- [x] #14
