### ISSUE TITLE
Database 구체화

### ISSUE THREAD

**Issue by green-21** [4-ak/sooot#34]
스미카를 더 구체화하고, postgreSQL을 공부한 다음 이를 마이그레이션 한다.

### todos
- [x] 데이터베이스 erd 작성
- [x] lecture 테이블 분리
- [x] 데이터베이스 테이블 재정의
- [x] #56
