### ISSUE TITLE
비밀번호 암호화

### ISSUE THREAD

**Issue by green-21** [4-ak/sooot#9]
비밀번호를 안전하게 전송하고 보관하는 방법에 대해 연구하고 적용한다.

## todos
- [x] 서버 입장에서 비밀번호를 안전하게 보관하는 방법에 대해 조사한다.
- [x] golang으로 이를 실습해본다.
- [x] 프로젝트에 적용한다.
- [x] 문서로 남긴다.
- [x] 클라이언트 입장에서 비밀번호를 안전하게 전송하는 방법에 대해서 조사한다.
- [x] 실습한다.
- [x] 프로젝트에 적용한다.
- [x] 문서로 남긴다.
